Создана CRUD логика Покупателя
OurBookStore/TheBookStore pull request #13
Opened 2023-07-04 20:25 UTC by alekseiiagnenkov

Так же немного доработал логику книг и исправил пару моментов

Покрытие бизнесс логики 100%

2023-07-06 19:59 UTC, garlik6 approved these changes

2023-07-07 07:17 UTC, SlaykSD commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
Считают, что под каждый тест должны подвязываться только те сущности, которые используется в тесте.  При этом возможно реализовать запуск spring boot приложения 1 раз на все тесты. Просто использовав @SpringBootTest 
https://stackoverflow.com/questions/45591160/use-one-spring-boot-context-through-all-springboottests

2023-07-07 07:24 UTC, SlaykSD requested changes
В остальном все нормально. По мелочи - на controller не поставил javadoc своего авторства, пробелы  от названия не поставил на exception :)

2023-07-07 07:43 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
"При этом возможно реализовать запуск spring boot приложения 1 раз на все тесты. Просто использовав https://github.com/SpringBootTest
https://stackoverflow.com/questions/45591160/use-one-spring-boot-context-through-all-springboottests"

2023-07-07 07:46 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
Идея этого класса в том, что он нужен только для каких то базовых вещей и инжекта. Ты уверен, что эти репозитории/контроллеры(бины в общем) не понадобятся в других тестах? Я - нет. Сейчас тесты будут обрастать новой логикой, все может быть. Это нормальная практика создавать центральный класс для инжекта и запуска @SpringBootTest

2023-07-07 07:49 UTC, SlaykSD commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
Я вижу избыточный inject в и дальнейшем так и будет

2023-07-07 07:50 UTC, SlaykSD commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
Где-то будут инжектится одни бины, где-то другие, а где-то лишнее

2023-07-07 07:51 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
они инжектятся 1 раз

2023-07-07 07:52 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
Все текущие инжекты используются, не понял твой кейс про избыточность

2023-07-07 08:00 UTC, SlaykSD commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
Не вижу использования BookController и BookRrepository в тестах CustomerTests

2023-07-07 08:02 UTC, alekseiiagnenkov commented on src/test/java/ru/mephi/ourbookstore/BookStoreTest.java
> +    CustomerController customerController;
Правильно, потому что они используются в других тестах. Но я не могу гарантировать, что когда мы обрастем логикой, у нас не будет использований Book... в CustomerTests. Предлагаю выбрать просто 1 вариант, я описал в ТГ. И его придерживаться. Это похоже на холиварную тему, и в твоем подходе есть плюсы, и в моем

2023-07-07 08:44 UTC, SlaykSD approved these changes

2023-07-07 08:44 UTC, merged