Create cart logic
OurBookStore/TheBookStore pull request #42
Opened 2023-11-01 08:40 UTC by alekseiiagnenkov

2023-11-01 17:02 UTC, mirinion requested changes

2023-11-01 17:02 UTC, mirinion commented on src/main/java/ru/mephi/ourbookstore/service/orderPosition/OrderPositionService.java
> +    public void addToCart(long orderPositionId, long cartId) {
разве тут не нужна @Transactional? Мы ж сейвим в датабазу

2023-11-01 17:14 UTC, mirinion commented on src/main/java/ru/mephi/ourbookstore/service/orderPosition/OrderPositionService.java
> +    public void removeFromCart(long orderPositionId) {
И тут тоже @ transactional

2023-11-02 13:36 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/ourbookstore/service/appUser/AppUserService.java
> +        createCartFromAppUser(appUser);
Я не уверен, что этот метод останется таким же маленьким, по этому пускай будет так. Мб потом придется что-то еще добавить сюда

2023-11-02 13:37 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/ourbookstore/service/orderPosition/OrderPositionService.java
> +    public void addToCart(long orderPositionId, long cartId) {
Факты, онли факты)

2023-11-02 16:13 UTC, mirinion approved these changes

2023-11-02 17:01 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/controller/orderPosition/OrderPositionController.java
> +    @PutMapping("/add-to-cart")
Не лучший вариант выбора API. Лера уже поясняла за REST, что ручки не должны говорить о том, что по ним делается

2023-11-02 17:05 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/controller/orderPosition/OrderPositionController.java
> +    @PutMapping("/add-to-cart")
Кстати мне не очень нравится что запрос в коде называется add to cart , по причине того, что уже обозначил именование операций по линковке addLink. Но это мелочь

2023-11-02 17:07 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/ourbookstore/controller/orderPosition/OrderPositionController.java
> +    @PutMapping("/add-to-cart")
Осуждаешь - предлагай. В данном контроллере уже есть ручка с PUT

2023-11-02 17:10 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/controller/orderPosition/OrderPositionController.java
> +    @PutMapping("/add-to-cart")
Для REST'а справедливо было бы именование ручки
POST (/positions/uuid-pos/cart/uuid-cart)

2023-11-02 17:11 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/controller/orderPosition/OrderPositionController.java
> +    @PutMapping("/add-to-cart")
Если тебе не хочется менять DTO. То просто positions/carts

2023-11-02 17:15 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/service/appUser/AppUserService.java
> +    private void createCartFromAppUser(AppUser appUser) {
Да, конечно выглядит прямо как избыточный код. Можешь хотя бы пример привести расширения этой функции?

2023-11-02 17:16 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/service/cart/CartService.java
> +    public Cart createEmptyCart() {
То же самое про избыточность

2023-11-02 17:18 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/ourbookstore/service/cart/CartService.java
> +    public Cart createEmptyCart() {
Я бы сказал, что это все условно, и никак не влияет на код, делает его читабельным. НО если это вас прям сильно задевает, а уберу. Лично мне приятнее так читать @SlaykSD @mirinion

2023-11-02 17:18 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/domain/OrderPositionModel.java
> +    @ManyToOne(cascade = {CascadeType.MERGE})
Не увидел применения

2023-11-02 17:18 UTC, alekseiiagnenkov commented on src/main/java/ru/mephi/ourbookstore/service/appUser/AppUserService.java
> +    private void createCartFromAppUser(AppUser appUser) {
Создание корзины может начать подразумевать под собой что-то еще. Так же сама стартовая корзина может начать иметь какое то состояние

2023-11-02 17:24 UTC, SlaykSD commented on src/main/java/ru/mephi/ourbookstore/service/appUser/AppUserService.java
> +    private void createCartFromAppUser(AppUser appUser) {
Ты точно думаешь, что мы будем реализовывать эту фичу?) 
Вообще не понимаю про какое состояние может вообще когда-то идти речь

2023-11-02 17:46 UTC, SlaykSD approved these changes

2023-11-02 17:52 UTC, merged